### ISSUE TITLE
TODO List from August 26

### ISSUE THREAD

**Issue by ogulcanbs** [WayGold/EAE_RP_Project1#3]
- [x] 1. Create TeaBubble Class and PNG, Floating Animation and Randomize Generate Bubbles at Right Half of Display
- [x] 2. Life system and life png
- [x] 3. Blinking when collision occurs
- [x] 4. Teapot Refilling System, Collision Detector for TeaBubble and Pot
- [ ] 5. start menu
- [x] 6. win screen display and png
- [ ] 7. 3 different maps design and integrate into start menu
- [x] 8. add tea deliver zone as built-in map data and drop-off checking system
- [x] 9. modify data parser to support reading tea deliver zone data

**Comment by MykaelaP** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Tea Drop Moving Through Obstacles Fix](https://trello.com/c/NuVhlw3K/24-tea-drop-moving-through-obstacles-fix)

**Comment by MykaelaP** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Start Menu](https://trello.com/c/mQiSR1L2/19-start-menu)

**Comment by MykaelaP** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Service System](https://trello.com/c/VxkPRJvP/22-service-system)

**Comment by MykaelaP** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Refueling System](https://trello.com/c/ujyBTrJI/41-refueling-system)

**Comment by MykaelaP** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Updated Game Over Menu](https://trello.com/c/tPRDMJ73/40-updated-game-over-menu)

**Comment by ogulcanbs** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Desing new map(s)](https://trello.com/c/EslbfM75/46-desing-new-maps)
